# =============================================================================
# k3s Kubernetes Cluster Module
# =============================================================================
# This module provisions a lightweight k3s Kubernetes cluster for self-hosted
# deployments. k3s is a certified Kubernetes distribution designed for
# resource-constrained environments.
#
# Supported deployments:
# - Single node (development)
# - Multi-node cluster (production)
# - Oracle Cloud Always Free Tier
# - Any VPS or bare metal server
# =============================================================================

terraform {
  required_providers {
    null = {
      source  = "hashicorp/null"
      version = "~> 3.2"
    }
    local = {
      source  = "hashicorp/local"
      version = "~> 2.4"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.6"
    }
  }
}

# =============================================================================
# Local Variables
# =============================================================================

locals {
  cluster_name = "cognive-${var.environment}"

  # k3s installation options
  k3s_install_options = join(" ", compact([
    "--disable=traefik", # We'll use our own Traefik configuration
    "--disable=servicelb",
    var.disable_local_storage ? "--disable=local-storage" : "",
    var.tls_san != "" ? "--tls-san=${var.tls_san}" : "",
    "--node-name=${local.cluster_name}-server",
    "--cluster-init",
  ]))

  # k3s agent options for worker nodes
  k3s_agent_options = join(" ", [
    "--node-name=${local.cluster_name}-agent",
  ])
}

# =============================================================================
# Generate k3s Token
# =============================================================================

resource "random_password" "k3s_token" {
  length  = 64
  special = false
}

# =============================================================================
# k3s Installation Script
# =============================================================================

resource "local_file" "k3s_install_script" {
  filename = "${path.module}/generated/install-k3s-server.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# k3s Server Installation Script
# Generated by Terraform for Cognive Control Plane
# Environment: ${var.environment}
# =============================================================================

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "$${GREEN}[INFO]$${NC} $1"; }
log_warn() { echo -e "$${YELLOW}[WARN]$${NC} $1"; }
log_error() { echo -e "$${RED}[ERROR]$${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# Check if k3s is already installed
if command -v k3s &> /dev/null; then
    log_warn "k3s is already installed. Skipping installation."
    log_info "To reinstall, run: /usr/local/bin/k3s-uninstall.sh"
    exit 0
fi

log_info "Installing k3s version: ${var.k3s_version}"

# Set k3s token
export K3S_TOKEN="${random_password.k3s_token.result}"

# Install k3s
curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION="${var.k3s_version}" \
    K3S_TOKEN="$K3S_TOKEN" \
    sh -s - server ${local.k3s_install_options}

# Wait for k3s to be ready
log_info "Waiting for k3s to be ready..."
sleep 10
until kubectl get nodes &> /dev/null; do
    log_info "Waiting for Kubernetes API..."
    sleep 5
done

# Copy kubeconfig to standard location
mkdir -p ~/.kube
cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
chmod 600 ~/.kube/config

# Display cluster info
log_info "k3s installation complete!"
kubectl get nodes
kubectl get pods -A

log_info "Kubeconfig saved to ~/.kube/config"
log_info "Join token for worker nodes: $K3S_TOKEN"
EOF

  file_permission = "0755"
}

# =============================================================================
# k3s Agent Installation Script (for worker nodes)
# =============================================================================

resource "local_file" "k3s_agent_script" {
  filename = "${path.module}/generated/install-k3s-agent.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# k3s Agent Installation Script (Worker Node)
# Generated by Terraform for Cognive Control Plane
# Environment: ${var.environment}
# =============================================================================

set -euo pipefail

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

log_info() { echo -e "$${GREEN}[INFO]$${NC} $1"; }
log_error() { echo -e "$${RED}[ERROR]$${NC} $1"; }

# Check if running as root
if [[ $EUID -ne 0 ]]; then
   log_error "This script must be run as root"
   exit 1
fi

# Required: K3S_URL and K3S_TOKEN must be set
if [[ -z "$${K3S_URL:-}" ]]; then
    log_error "K3S_URL environment variable is required"
    log_info "Example: export K3S_URL=https://server-ip:6443"
    exit 1
fi

if [[ -z "$${K3S_TOKEN:-}" ]]; then
    log_error "K3S_TOKEN environment variable is required"
    log_info "Get token from server: cat /var/lib/rancher/k3s/server/node-token"
    exit 1
fi

log_info "Installing k3s agent..."
log_info "Server URL: $K3S_URL"

# Install k3s agent
curl -sfL https://get.k3s.io | \
    INSTALL_K3S_VERSION="${var.k3s_version}" \
    K3S_URL="$K3S_URL" \
    K3S_TOKEN="$K3S_TOKEN" \
    sh -s - agent ${local.k3s_agent_options}

log_info "k3s agent installation complete!"
log_info "This node should now appear in the cluster."
EOF

  file_permission = "0755"
}

# =============================================================================
# k3s Uninstall Script
# =============================================================================

resource "local_file" "k3s_uninstall_script" {
  filename = "${path.module}/generated/uninstall-k3s.sh"
  content  = <<-EOF
#!/bin/bash
# =============================================================================
# k3s Uninstall Script
# Generated by Terraform for Cognive Control Plane
# =============================================================================

set -euo pipefail

echo "This will completely remove k3s from this machine."
read -p "Are you sure? (yes/no): " confirm

if [[ "$confirm" != "yes" ]]; then
    echo "Aborted."
    exit 0
fi

# Uninstall server
if [[ -f /usr/local/bin/k3s-uninstall.sh ]]; then
    /usr/local/bin/k3s-uninstall.sh
    echo "k3s server uninstalled."
fi

# Uninstall agent
if [[ -f /usr/local/bin/k3s-agent-uninstall.sh ]]; then
    /usr/local/bin/k3s-agent-uninstall.sh
    echo "k3s agent uninstalled."
fi

echo "k3s has been removed."
EOF

  file_permission = "0755"
}

# =============================================================================
# Kubernetes Namespace Manifest
# =============================================================================

resource "local_file" "cognive_namespace" {
  filename = "${path.module}/generated/namespace.yaml"
  content  = <<-EOF
---
apiVersion: v1
kind: Namespace
metadata:
  name: cognive
  labels:
    app.kubernetes.io/name: cognive
    app.kubernetes.io/component: control-plane
    environment: ${var.environment}
EOF

  file_permission = "0644"
}

# =============================================================================
# Outputs
# =============================================================================

output "k3s_token" {
  description = "k3s cluster join token"
  value       = random_password.k3s_token.result
  sensitive   = true
}

output "install_script_path" {
  description = "Path to k3s server installation script"
  value       = local_file.k3s_install_script.filename
}

output "agent_script_path" {
  description = "Path to k3s agent installation script"
  value       = local_file.k3s_agent_script.filename
}

output "uninstall_script_path" {
  description = "Path to k3s uninstall script"
  value       = local_file.k3s_uninstall_script.filename
}

output "namespace_manifest_path" {
  description = "Path to Cognive namespace manifest"
  value       = local_file.cognive_namespace.filename
}

output "cluster_name" {
  description = "k3s cluster name"
  value       = local.cluster_name
}

